const fs=require("fs"),path=require("path"),{execFileSync}=require("child_process");
class Kernel{
 constructor({root,provider}){this.root=root;this.provider=provider;this.base=path.join(root,".wfe-next");this.stateFile=path.join(this.base,"state.json");fs.mkdirSync(path.join(this.base,"workspaces"),{recursive:true});this.state=this.load()}
 load(){try{return JSON.parse(fs.readFileSync(this.stateFile,"utf8"))}catch{return{projects:{}}}} save(){fs.writeFileSync(this.stateFile,JSON.stringify(this.state,null,2))}
 project(id="playground"){return this.state.projects[id]??={id,name:"Playground",runs:[]}}
 plan(goal){return{goal,steps:[{id:"build",label:"Model-backed build"},{id:"check",label:"Deterministic artifact checks"},{id:"repair",label:"Model-backed repair if needed"},{id:"verify",label:"Independent final verification"}],acceptance:["satisfy the Goal as written","usable browser surface","self-contained local artifact"]}}
 async start({projectId="playground",goal,plan}){const p=this.project(projectId),id=`run-${Date.now()}`,workspace=path.join(this.base,"workspaces",id);fs.mkdirSync(workspace,{recursive:true});const run={id,goal,plan,workspace,status:"BUILDING",steps:[],decisions:[],diagnostics:[],artifacts:[],checks:[],verifier:null,startedAt:new Date().toISOString()};p.runs.push(run);this.save();try{await this.step(run,"BUILDING",async()=>{const o=await this.provider.implement({goal,plan,workspace});this.writeFiles(workspace,o.files);run.decisions.push(o.decision);if(o.diagnostic)run.diagnostics.push(o.diagnostic);run.product=o.product||this.readProduct(workspace);run.artifacts=this.artifacts(workspace)});let failures=await this.check(run,workspace);for(let n=1;failures.length&&n<=2;n++){await this.step(run,"REPAIRING",async()=>{const o=await this.provider.repair({goal,plan,failures,workspace});this.writeFiles(workspace,o.files);run.decisions.push(o.decision);if(o.diagnostic)run.diagnostics.push(o.diagnostic);run.product=o.product||this.readProduct(workspace);run.artifacts=this.artifacts(workspace)});failures=await this.check(run,workspace)}if(failures.length)throw new Error(`Checks still failing: ${failures.join("; ")}`);await this.step(run,"VERIFYING",async()=>{run.verifier=this.verify(workspace);if(!run.verifier.pass)throw new Error(run.verifier.failures.join("; "))});run.status="DONE";run.playUrl=`/play/${id}/index.html`;run.finishedAt=new Date().toISOString();this.save();return run}catch(e){run.status="BLOCKED";run.blocker=e.message;run.finishedAt=new Date().toISOString();this.save();return run}}
 async step(run,label,fn){const s={label,status:"RUNNING",startedAt:new Date().toISOString()};run.status=label;run.steps.push(s);this.save();try{await fn();s.status="DONE"}catch(e){s.status="FAILED";s.error=e.message;throw e}finally{s.finishedAt=new Date().toISOString();this.save()}}
 async check(run,w){run.status="CHECKING";this.save();const f=[];for(const name of ["index.html","product.json"])if(!fs.existsSync(path.join(w,name)))f.push(`${name} missing`);for(const file of this.artifacts(w).filter(x=>x.endsWith(".js")))try{execFileSync(process.execPath,["--check",path.join(w,file)],{stdio:"pipe"})}catch{f.push(`${file} syntax invalid`)}if(fs.existsSync(path.join(w,"index.html"))){const h=fs.readFileSync(path.join(w,"index.html"),"utf8");if(!/<(button|input|select|textarea|form)\b/i.test(h))f.push("browser surface has no interactive controls")}if(!this.readProduct(w))f.push("product.json invalid");run.checks.push({at:new Date().toISOString(),pass:!f.length,failures:f});this.save();return f}
 verify(w){const f=[],h=fs.existsSync(path.join(w,"index.html"))?fs.readFileSync(path.join(w,"index.html"),"utf8"):"",p=this.readProduct(w);if(!/<!doctype|<html/i.test(h))f.push("HTML application surface absent");if(!/<(button|input|select|textarea|form)\b/i.test(h))f.push("no usable interactive surface");if(!p?.title||!p?.summary)f.push("product record incomplete");for(const file of this.artifacts(w).filter(x=>x.endsWith(".js")))try{execFileSync(process.execPath,["--check",path.join(w,file)],{stdio:"pipe"})}catch{f.push(`${file} syntax invalid`)}return{pass:!f.length,failures:f,title:p?.title,at:new Date().toISOString()}}
 readProduct(w){try{return JSON.parse(fs.readFileSync(path.join(w,"product.json"),"utf8"))}catch{return null}} artifacts(w){return fs.readdirSync(w).filter(x=>!x.startsWith("."))} writeFiles(w,files={}){for(const[n,b]of Object.entries(files)){const f=path.join(w,n);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,b)}}
}
module.exports={Kernel};