const fs=require("fs"),path=require("path"),{execFileSync}=require("child_process");
class Kernel {
 constructor({root,provider}){this.root=root;this.provider=provider;this.base=path.join(root,".wfe-next");this.stateFile=path.join(this.base,"state.json");fs.mkdirSync(path.join(this.base,"workspaces"),{recursive:true});this.state=this.load()}
 load(){try{return JSON.parse(fs.readFileSync(this.stateFile,"utf8"))}catch{return {projects:{}}}}
 save(){fs.writeFileSync(this.stateFile,JSON.stringify(this.state,null,2))}
 project(id="pong"){return this.state.projects[id]??={id,name:"Pong Playground",runs:[]}}
 plan(goal){return {goal,steps:[{id:"build",label:"Build browser game"},{id:"test",label:"Run deterministic checks"},{id:"repair",label:"Repair bounded failures"},{id:"verify",label:"Verify playable acceptance"}],acceptance:["browser-playable Pong","keyboard controls","opponent and scoring","restart","original gravity-well twist"]}}
 async start({projectId="pong",goal,plan}){const p=this.project(projectId),id=`run-${Date.now()}`,workspace=path.join(this.base,"workspaces",id);fs.mkdirSync(workspace,{recursive:true});const run={id,goal,plan,workspace,status:"RUNNING",steps:[],decisions:[],artifacts:[],checks:[],verifier:null,startedAt:new Date().toISOString()};p.runs.push(run);this.save();
  try{await this.step(run,"BUILD",async()=>{const o=await this.provider.implement({goal,plan});this.writeFiles(workspace,o.files);run.decisions.push(o.decision);run.artifacts=Object.keys(o.files)});
   let failures=await this.check(run,workspace);for(let n=1;failures.length&&n<=2;n++){await this.step(run,`REPAIR ${n}`,async()=>{const o=await this.provider.repair({goal,plan,failures,workspace});this.writeFiles(workspace,o.files);run.decisions.push(o.decision);run.artifacts=[...new Set([...run.artifacts,...Object.keys(o.files)])]});failures=await this.check(run,workspace)}
   if(failures.length)throw new Error(`Checks still failing: ${failures.join("; ")}`);await this.step(run,"VERIFY",async()=>{const v=this.verify(workspace);run.verifier=v;if(!v.pass)throw new Error(v.failures.join("; "))});run.status="DONE";run.playUrl=`/play/${id}/index.html`;run.finishedAt=new Date().toISOString();this.save();return run;
  }catch(e){run.status="BLOCKED";run.blocker=e.message;run.finishedAt=new Date().toISOString();this.save();return run}}
 async step(run,label,fn){const s={label,status:"RUNNING",startedAt:new Date().toISOString()};run.steps.push(s);this.save();try{await fn();s.status="DONE"}catch(e){s.status="FAILED";s.error=e.message;throw e}finally{s.finishedAt=new Date().toISOString();this.save()}}
 async check(run,w){const f=[];try{execFileSync(process.execPath,["--check",path.join(w,"game.js")],{stdio:"pipe"})}catch{f.push("game.js syntax invalid")}const g=fs.readFileSync(path.join(w,"game.js"),"utf8"),h=fs.readFileSync(path.join(w,"index.html"),"utf8");for(const [ok,msg] of [[h.includes("<canvas"),"canvas missing"],[g.includes("keydown"),"keyboard controls missing"],[g.includes("score"),"scoring missing"],[g.includes("reset"),"restart missing"],[g.includes("gravityWell"),"original gravity-well twist missing"]])if(!ok)f.push(msg);run.checks.push({at:new Date().toISOString(),pass:!f.length,failures:f});this.save();return f}
 verify(w){const g=fs.readFileSync(path.join(w,"game.js"),"utf8"),h=fs.readFileSync(path.join(w,"index.html"),"utf8"),f=[];if(!h.includes("game.js"))f.push("game script not exposed");if(!g.includes("requestAnimationFrame"))f.push("game loop missing");if(!g.includes("gravityWell"))f.push("twist not verified");return {pass:!f.length,failures:f,at:new Date().toISOString()}}
 writeFiles(w,files){for(const [n,b] of Object.entries(files)){const f=path.join(w,n);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,b)}}
}
module.exports={Kernel};
