const fs=require("fs"),path=require("path"),{execFileSync}=require("child_process");
class Kernel{
 constructor({root,provider}){this.root=root;this.provider=provider;this.base=path.join(root,".wfe-next");this.stateFile=path.join(this.base,"state.json");fs.mkdirSync(path.join(this.base,"workspaces"),{recursive:true});this.state=this.load()}
 load(){try{return JSON.parse(fs.readFileSync(this.stateFile,"utf8"))}catch{return{projects:{}}}} save(){fs.writeFileSync(this.stateFile,JSON.stringify(this.state,null,2))}
 project(id="pong"){return this.state.projects[id]??={id,name:"Playground",runs:[]}}
 plan(goal){return{goal,steps:[{id:"build",label:"Model-backed build"},{id:"check",label:"Deterministic product checks"},{id:"repair",label:"Model-backed repair if needed"},{id:"verify",label:"Independent final verification"}],acceptance:["browser-playable Pong-style game","documented keyboard controls","opponent and visible scoring","restart","model-chosen original twist"]}}
 async start({projectId="pong",goal,plan}){const p=this.project(projectId),id=`run-${Date.now()}`,workspace=path.join(this.base,"workspaces",id);fs.mkdirSync(workspace,{recursive:true});const run={id,goal,plan,workspace,status:"BUILDING",steps:[],decisions:[],diagnostics:[],artifacts:[],checks:[],verifier:null,startedAt:new Date().toISOString()};p.runs.push(run);this.save();
 try{await this.step(run,"BUILDING",async()=>{const o=await this.provider.implement({goal,plan,workspace});this.writeFiles(workspace,o.files);run.decisions.push(o.decision);if(o.diagnostic)run.diagnostics.push(o.diagnostic);run.product=o.product||this.readProduct(workspace);run.artifacts=this.artifacts(workspace)});
 let failures=await this.check(run,workspace);for(let n=1;failures.length&&n<=2;n++){await this.step(run,"REPAIRING",async()=>{const o=await this.provider.repair({goal,plan,failures,workspace});this.writeFiles(workspace,o.files);run.decisions.push(o.decision);if(o.diagnostic)run.diagnostics.push(o.diagnostic);run.product=o.product||this.readProduct(workspace);run.artifacts=this.artifacts(workspace)});failures=await this.check(run,workspace)}
 if(failures.length)throw new Error(`Checks still failing: ${failures.join("; ")}`);await this.step(run,"VERIFYING",async()=>{run.verifier=this.verify(workspace);if(!run.verifier.pass)throw new Error(run.verifier.failures.join("; "))});run.status="DONE";run.playUrl=`/play/${id}/index.html`;run.finishedAt=new Date().toISOString();this.save();return run}catch(e){run.status="BLOCKED";run.blocker=e.message;run.finishedAt=new Date().toISOString();this.save();return run}}
 async step(run,label,fn){const s={label,status:"RUNNING",startedAt:new Date().toISOString()};run.status=label;run.steps.push(s);this.save();try{await fn();s.status="DONE"}catch(e){s.status="FAILED";s.error=e.message;throw e}finally{s.finishedAt=new Date().toISOString();this.save()}}
 async check(run,w){run.status="CHECKING";this.save();const f=[];for(const name of ["index.html","game.js","product.json"])if(!fs.existsSync(path.join(w,name)))f.push(`${name} missing`);if(f.length){run.checks.push({pass:false,failures:f});this.save();return f}try{execFileSync(process.execPath,["--check",path.join(w,"game.js")],{stdio:"pipe"})}catch{f.push("game.js syntax invalid")}
 const g=fs.readFileSync(path.join(w,"game.js"),"utf8"),h=fs.readFileSync(path.join(w,"index.html"),"utf8"),p=this.readProduct(w);for(const [ok,msg] of [[/<canvas/i.test(h),"canvas missing"],[/keydown|keyup|keyCode|KeyboardEvent/i.test(g),"keyboard controls missing"],[/score/i.test(g+h),"visible scoring implementation missing"],[/restart|reset/i.test(g+h),"restart missing"],[typeof p?.twist==="string"&&p.twist.trim().length>=8,"model-chosen twist not declared"],[/requestAnimationFrame|setInterval/i.test(g),"game loop missing"],[typeof p?.twist==="string"&&h.toLowerCase().includes(p.twist.trim().toLowerCase()),"twist explanation is not visibly present verbatim in index.html"]])if(!ok)f.push(msg);run.checks.push({at:new Date().toISOString(),pass:!f.length,failures:f});this.save();return f}
 verify(w){const f=[],p=this.readProduct(w),g=fs.readFileSync(path.join(w,"game.js"),"utf8"),h=fs.readFileSync(path.join(w,"index.html"),"utf8");if(!/game\.js/i.test(h))f.push("game script not exposed");if(!p?.twist)f.push("twist absent from product record");if(!/score/i.test(g)||!/canvas/i.test(h))f.push("core Pong surface absent");return{pass:!f.length,failures:f,twist:p?.twist,at:new Date().toISOString()}}
 readProduct(w){try{return JSON.parse(fs.readFileSync(path.join(w,"product.json"),"utf8"))}catch{return null}} artifacts(w){return fs.readdirSync(w).filter(x=>!x.startsWith("."))} writeFiles(w,files={}){for(const[n,b]of Object.entries(files)){const f=path.join(w,n);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,b)}}
}
module.exports={Kernel};