const LIFECYCLES=['ACTIVE','INACTIVE','ARCHIVED'],PURPOSES=['USER_PROJECT','ACCEPTANCE_FIXTURE','RECOVERY_TEST','PLAYGROUND_EXPERIMENT','LEGACY_UNKNOWN'],PROTECTIONS=['NORMAL','WARN_BEFORE_MUTATION'];
const purposeLabel=p=>({USER_PROJECT:'USER PROJECT',ACCEPTANCE_FIXTURE:'ACCEPTANCE FIXTURE',RECOVERY_TEST:'RECOVERY / TEST',PLAYGROUND_EXPERIMENT:'PLAYGROUND / EXPERIMENT',LEGACY_UNKNOWN:'LEGACY / UNKNOWN'})[p]||'LEGACY / UNKNOWN';
function metadata(p){return p.metadata||{lifecycle:'INACTIVE',purpose:'LEGACY_UNKNOWN',protection:'WARN_BEFORE_MUTATION',source:'No recorded provenance'};}
function validateMetadata(m){if(!m||!LIFECYCLES.includes(m.lifecycle)||!PURPOSES.includes(m.purpose)||!PROTECTIONS.includes(m.protection))throw Error('invalid Project metadata');return {lifecycle:m.lifecycle,purpose:m.purpose,protection:m.protection,source:'Explicit operator classification',updatedAt:new Date().toISOString()};}
function mutationAllowed(p,confirmed){if(metadata(p).protection==='WARN_BEFORE_MUTATION'&&confirmed!==true)throw Error('PROJECT_PROTECTED: Changes may invalidate regression evidence. Explicitly continue before mutation.');}
function projectStatus(p,active=[]){const runs=p.runs||[],latest=runs.at(-1),accepted=runs.filter(r=>r.status==='DONE').at(-1)||null,busy=active.includes(p.id),goal=busy?latest?.goal:p.pendingGoal??latest?.goal??null,run=latest&&latest.goal===goal?latest:null,prepared=p.preparedPlan,planReady=!!prepared&&prepared.goal===goal;
 const interrupted=run&&!['DONE','BLOCKED'].includes(run.status)&&!busy;
 const state=busy?'RUNNING':planReady?'READY':interrupted?'BLOCKED':run?.status||'NO ACTIVE WORK';
 const times=[p.createdAt,p.goalUpdatedAt,prepared?.createdAt,...runs.flatMap(r=>[r.startedAt,r.finishedAt,r.openEvidence?.at,r.verifier?.at,...(r.steps||[]).flatMap(s=>[s.startedAt,s.finishedAt]),...(r.checks||[]).map(x=>x.at),...(r.behavior||[]).map(x=>x.at)])].filter(x=>typeof x==='string'&&Number.isFinite(Date.parse(x))).sort((a,b)=>Date.parse(b)-Date.parse(a));
 const step=busy?(run?.steps||[]).findLast(s=>s.status==='RUNNING'):run?.steps?.at(-1);
 return {metadata:metadata(p),runs:runs.length,acceptedRuns:runs.filter(r=>r.status==='DONE').length,goal,currentRun:run?.id||null,currentStep:step?step.label+' · '+step.status:busy?run?.status||'Unavailable':'None',state,execution:busy?'Local WFE operator execution · provider owner unavailable':interrupted?'Interrupted / no live execution evidence':'NO ACTIVE RUN',startedAt:busy?run?.startedAt||null:null,planReady,acceptedResult:accepted?.id||null,lastActivity:times[0]||null,interrupted};}
module.exports={LIFECYCLES,PURPOSES,PROTECTIONS,purposeLabel,metadata,validateMetadata,mutationAllowed,projectStatus};
