const fs=require("fs"),path=require("path"),{spawnSync,spawn}=require("child_process");
class Provider{async implement(){throw new Error("implement not configured")}async repair(){throw new Error("repair not configured")}}
class CodexProvider extends Provider{
 constructor({command="codex"}={}){super();this.command=command}
 async implement({goal,plan,workspace}){return this.run(workspace,`You are WFE-Next's implementation provider. Work ONLY inside the current disposable workspace. Build the requested browser game from scratch. Goal: ${goal}\nPlan: ${JSON.stringify(plan)}\nCreate index.html, style.css, game.js and product.json. product.json must be JSON with {"title":string,"twist":string,"summary":string}. Choose the original twist yourself; do not use a gravity well unless independently chosen. Requirements: immediately playable Pong-style game, keyboard controls documented on screen, opponent, visible scoring, restart, original twist visibly explained. No dependencies, network, build tools, markdown, or questions. Actually write the files, then stop.`)}
 async repair({goal,plan,failures,workspace}){return this.run(workspace,`Repair the existing browser game in the current workspace. Goal: ${goal}\nPlan: ${JSON.stringify(plan)}\nDeterministic check failures: ${JSON.stringify(failures)}\nInspect the current files, make the smallest real code/content changes needed to satisfy every failure while preserving the model-chosen twist. Do not merely change product.json to claim success. Do not ask questions. Write fixes directly, then stop.`)}
 run(workspace,prompt){const exe=process.platform==="win32"?process.execPath:this.command,args=process.platform==="win32"?["C:/Users/Pavel/AppData/Roaming/npm/node_modules/@openai/codex/bin/codex.js","exec","--ephemeral"]:["exec","--ephemeral"];const r=spawnSync(exe,[...args,"--skip-git-repo-check","-s","workspace-write","-C",workspace,"-"],{input:prompt,encoding:"utf8",timeout:240000,windowsHide:true});if(r.error)throw r.error;if(r.status!==0)throw new Error(`model executor failed (${r.status}): ${(r.stderr||r.stdout||"").slice(-1200)}`);const files=["index.html","style.css","game.js","product.json"].filter(x=>fs.existsSync(path.join(workspace,x)));if(!files.includes("index.html")||!files.includes("game.js")||!files.includes("product.json"))throw new Error("model did not produce required files");let product;try{product=JSON.parse(fs.readFileSync(path.join(workspace,"product.json"),"utf8"))}catch{throw new Error("product.json is invalid")};return{files:{},decision:`Model produced ${files.join(", ")}; twist: ${product.twist||"UNDECLARED"}`,diagnostic:(r.stdout||"").trim().slice(-600),product}}
}
class ClaudeProvider extends Provider{
 async implement({goal,plan,workspace}){return this.run(workspace,`You are WFE-Next's implementation provider. Work only in this disposable workspace. Build the requested browser game from scratch. Goal: ${goal}\nPlan: ${JSON.stringify(plan)}\nCreate index.html, style.css, game.js and product.json. product.json must contain JSON keys title, twist, summary. You choose the original twist; WFE does not know it in advance. Make the game immediately understandable/playable with documented keyboard controls, opponent, visible scoring, restart, and visibly explain the twist. No dependencies, network, build tools, markdown, or questions. Write the actual files and stop.`)}
 async repair({goal,plan,failures,workspace}){return this.run(workspace,`Repair the existing browser game. Goal: ${goal}\nPlan: ${JSON.stringify(plan)}\nDeterministic failures: ${JSON.stringify(failures)}\nInspect current files and make the smallest real implementation changes satisfying every failure while preserving the chosen twist. Do not fake metadata. Write fixes directly and stop; ask no questions.`)}
 run(workspace,prompt){return new Promise((resolve,reject)=>{const exe=process.env.WFE_MODEL_COMMAND||"claude",cp=spawn(exe,["-p","--permission-mode","bypassPermissions","--allowedTools","Write,Edit,Read"],{cwd:workspace,windowsHide:true,stdio:["pipe","pipe","pipe"]});let out="",err="";const timer=setTimeout(()=>{cp.kill();reject(new Error("model executor timeout"))},240000);cp.stdout.on("data",d=>out+=d);cp.stderr.on("data",d=>err+=d);cp.on("error",e=>{clearTimeout(timer);reject(e)});cp.on("close",code=>{clearTimeout(timer);if(code!==0)return reject(new Error(`model executor failed (${code}): ${(err||out).slice(-1200)}`));const files=["index.html","style.css","game.js","product.json"].filter(x=>fs.existsSync(path.join(workspace,x)));if(!files.includes("index.html")||!files.includes("game.js")||!files.includes("product.json"))return reject(new Error("model did not produce required files"));let product;try{product=JSON.parse(fs.readFileSync(path.join(workspace,"product.json"),"utf8"))}catch{return reject(new Error("product.json is invalid"))}resolve({files:{},decision:`Model produced ${files.join(", ")}; twist: ${product.twist||"UNDECLARED"}`,diagnostic:out.trim().slice(-600),product})});cp.stdin.end(prompt)})}
}
class DeterministicPongProvider extends Provider{
 async implement({goal}){const index='<!doctype html><html><body><p>W/S · R restart</p><p>Moving gravity well bends the ball</p><canvas id="game"></canvas><script src="game.js"></script></body></html>';return{files:{"index.html":index,"style.css":"","game.js":gameSource(false),"product.json":JSON.stringify({title:"Gravity Pong",twist:"Moving gravity well bends the ball",summary:goal})},decision:"Regression fixture initial candidate"}}
 async repair(){return{files:{"game.js":gameSource(true)},decision:"Regression fixture repair"}}
}
function gameSource(ok){return `${ok?'':'const =;'}const canvas=document.querySelector("canvas"),c=canvas.getContext("2d");let score=[0,0],ball={x:50,y:50};addEventListener("keydown",e=>{if(e.key==="r")reset()});function reset(){score=[0,0]}${ok?'const twistMechanic=true;':''}function loop(){c.clearRect(0,0,300,150);c.fillText(score.join(" : "),120,20);requestAnimationFrame(loop)}loop();`}
module.exports={Provider,CodexProvider,ClaudeProvider,DeterministicPongProvider};