const fs=require("fs"),path=require("path"),{spawn}=require("child_process");
class Provider{async implement(){throw new Error("implement not configured")}async repair(){throw new Error("repair not configured")}}
class ClaudeProvider extends Provider{
 async implement({goal,plan,workspace}){return this.run(workspace,`You are WFE-Next's implementation provider. Work only inside this disposable workspace. Build the browser application described by the Goal. Goal: ${goal}\nPlan: ${JSON.stringify(plan)}\nChoose the visual design, data model, filenames and implementation details yourself. The result must be a self-contained browser app runnable by opening/serving index.html, with no network or build step. Create product.json containing JSON keys title and summary, plus any application files you need. Implement the Goal completely; do not ask questions. Write the actual files and stop.`)}
 async repair({goal,plan,failures,workspace}){return this.run(workspace,`Repair the existing browser application in this workspace. Goal: ${goal}\nPlan: ${JSON.stringify(plan)}\nDeterministic failures: ${JSON.stringify(failures)}\nInspect the current artifact and make the smallest real implementation changes needed to satisfy every failure while preserving working behavior. Do not fake metadata or tests. Ask no questions. Write fixes directly and stop.`)}
 run(workspace,prompt){return new Promise((resolve,reject)=>{const exe=process.env.WFE_MODEL_COMMAND||"claude",cp=spawn(exe,["-p","--permission-mode","bypassPermissions","--allowedTools","Write,Edit,Read"],{cwd:workspace,windowsHide:true,stdio:["pipe","pipe","pipe"]});let out="",err="";const timer=setTimeout(()=>{cp.kill();reject(new Error("model executor timeout"))},240000);cp.stdout.on("data",d=>out+=d);cp.stderr.on("data",d=>err+=d);cp.on("error",e=>{clearTimeout(timer);reject(e)});cp.on("close",code=>{clearTimeout(timer);if(code!==0)return reject(new Error(`model executor failed (${code}): ${(err||out).slice(-1200)}`));const files=fs.readdirSync(workspace).filter(x=>!x.startsWith("."));if(!files.includes("index.html")||!files.includes("product.json"))return reject(new Error("model did not produce index.html and product.json"));let product;try{product=JSON.parse(fs.readFileSync(path.join(workspace,"product.json"),"utf8"))}catch{return reject(new Error("product.json is invalid"))}resolve({files:{},decision:`Model produced ${files.join(", ")}; product: ${product.title||"UNTITLED"}`,diagnostic:out.trim().slice(-600),product})});cp.stdin.end(prompt)})}
}
class DeterministicPongProvider extends Provider{
 async implement({goal}){return{files:{"index.html":'<html><body><button>Restart</button><canvas></canvas><script src="game.js"></script></body></html>',"game.js":"const =;","product.json":JSON.stringify({title:"Gravity Pong",summary:goal})},decision:"Regression fixture initial candidate"}}
 async repair(){return{files:{"game.js":'const canvas=document.querySelector("canvas");'},decision:"Regression fixture repair"}}
}
module.exports={Provider,ClaudeProvider,DeterministicPongProvider};