const http=require("http"),fs=require("fs"),path=require("path"),{Kernel}=require("./kernel"),{ClaudeProvider}=require("./provider");
const root=path.resolve(__dirname,".."),kernel=new Kernel({root,provider:new ClaudeProvider()}),active=new Set(),opened=new Map();
const send=(r,c,b,t="application/json")=>{r.writeHead(c,{"content-type":t});r.end(t.includes("json")?JSON.stringify(b):b)},body=q=>new Promise((ok,no)=>{let b="";q.on("data",x=>b+=x);q.on("end",()=>{try{ok(b?JSON.parse(b):{})}catch(e){no(e)}})});
const start=async x=>{active.add(x.projectId);const old=opened.get(x.projectId);if(old){await old.app.stop();opened.delete(x.projectId)}Promise.resolve(kernel.projectWorkspace(x.projectId)?kernel.evolve(x):kernel.start(x)).finally(()=>active.delete(x.projectId))};
const {workspaceFiles,workspaceSearch}=require('./workspace-files');
const loadedCode=require('crypto').createHash('sha256').update(['src/server.js','src/kernel.js','src/provider.js','src/plan-output.js','src/workspace-files.js','src/browser-runtime.js','src/browser-procedure.js','scripts/browser-executor.js'].map(f=>fs.readFileSync(path.join(root,f))).join('')).digest('hex');
const srv=http.createServer(async(q,r)=>{try{
if(q.method==="GET"&&q.url==="/")return send(r,200,fs.readFileSync(path.join(root,"ui/index.html"),"utf8"),"text/html");
if(q.method==='GET'&&q.url.startsWith('/api/search/')){const u=new URL(q.url,'http://127.0.0.1');try{return send(r,200,await workspaceSearch(kernel,decodeURIComponent(u.pathname.slice(12)),u.searchParams.get('q')))}catch(e){return send(r,400,{error:e.message})}}
if(q.method==='GET'&&q.url.startsWith('/api/files/')){const u=new URL(q.url,'http://127.0.0.1');try{return send(r,200,workspaceFiles(kernel,decodeURIComponent(u.pathname.slice(11)),u.searchParams.get('path')||''))}catch(e){return send(r,400,{error:e.message})}}
if(q.method==="GET"&&q.url==="/api/state"){for(const [id,x]of opened)if(!x.app.alive())opened.delete(id);return send(r,200,{...kernel.state,operator:{pid:process.pid,root,loadedCode,startedAt:new Date(Date.now()-process.uptime()*1000).toISOString()},active:[...active],opened:Object.fromEntries([...opened].map(([k,v])=>[k,{url:v.url,pid:v.pid,port:v.port}]))});}
if(q.method==="POST"&&q.url==="/api/projects")return send(r,201,kernel.createProject(await body(q)));
if(q.method==="POST"&&q.url==="/api/plan"){const x=await body(q);return send(r,200,await kernel.plan(x.goal,x.projectId))}
if(q.method==="POST"&&q.url==="/api/start"){const x=await body(q);if(active.has(x.projectId))return send(r,409,{error:"project active"});await start(x);return send(r,202,{accepted:true})}
if(q.method==='POST'&&q.url.startsWith('/api/close/')){const id=decodeURIComponent(q.url.slice(11)),x=opened.get(id);if(x){await x.app.stop();opened.delete(id)}return send(r,200,{closed:true})}
if(q.method==="POST"&&q.url.startsWith("/api/open/")){const id=decodeURIComponent(q.url.slice(10)),p=kernel.state.projects[id],run=p?.runs?.at(-1);if(active.has(id))return send(r,409,{error:"project active"});if(!run||run.status!=="DONE")return send(r,404,{error:"accepted result unavailable"});if(opened.has(id)){await opened.get(id).app.stop();opened.delete(id)}const x=await kernel.openAccepted(run);opened.set(id,x);return send(r,200,{url:x.url,pid:x.pid,port:x.port,ready:x.ready,owned:x.owned})}
send(r,404,{error:"not found"})}catch(e){send(r,500,{error:e.message})}});
async function stop(){for(const x of opened.values())await x.app.stop();srv.close(()=>process.exit(0))}process.on("SIGINT",stop);process.on("SIGTERM",stop);srv.listen(4317,"127.0.0.1",()=>console.log("WFE-Next Operator http://127.0.0.1:4317"));
